Update patch set 3
Patch Set 3: Code-Review-1

This is the complaint from coala:
Project wide:
|    | [NORMAL] GitCommitBear:
|    | Shortlog of HEAD commit isn't in imperative mood! Bad words are 'Updated'
Executing section Markdown...
Executing section reStructuredText...
Executing section cli...
ERROR: InvocationError: '/w/workspace/docs-tox-verify-oxygen/.tox/coala/bin/coala --non-interactive'

Need to use "Update" instead of "Updated".  As you are still working on the original patch, probably should stick with the original commit message: "Add oxygen m0 status for ..." - Just the first line needs to be <= 50 chars, you can add a blank line and then additional information.  The fact that you are updating openflow can be found via the code review messages.  Thanks!

Patch-set: 3
Label: Code-Review=-1