Updated git submodules
Project: netvirt stable/carbon 1a55cb7db08b778321e2760df653ed58445a1540

Bug 8863: NPE at VpnFloatingIpHandler

Problem Description:
=======================
The following exception was observed from VpnFloatingIpHandler in CSIT

Error in generate label or fib install process
java.lang.NullPointerException: Supplied value may not be null
org.opendaylight.netvirt.natservice.internal.VpnFloatingIpHandler.lambda$onAddFloatingIp$0(VpnFloatingIpHandler.java:194)[307:org.opendaylight.netvirt.natservice-impl:0.5.0.SNAPSHOT]

Solution:
=========
We need to enhance the pre-condition check in VpnFloatingIpHandler before
proceeding with any DNAT flow installation.

Have added the required null check for floatingIp ADD/REMOVE methods.

Change-Id: Ic516f8afc325a1e6eb515481abb2d0fef411336a
Signed-off-by: karthikeyan <karthikeyan.k@altencalsoftlabs.com>