Update patch set 1
Patch Set 1: Code-Review-1

(2 comments)

Please correct the two typos related to "it's" - should be "its".
Also, Verified is failing because of the commit message - need to shorten it:
Project wide:
|    | [NORMAL] GitCommitBear:
|    | Shortlog of the HEAD commit contains 75 character(s). This is 25 character(s) longer than the limit (75 > 50).
Executing section Markdown...
Executing section reStructuredText...
Executing section cli...
ERROR: InvocationError: '/w/workspace/docs-tox-verify-oxygen/.tox/coala/bin/coala --non-interactive'

Patch-set: 1
Reviewer: Gerrit User 7493 <7493@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1