Updated git submodules
Project: genius master d9ec57d4221793a63cce75d8cca4aab473025aa0

Must always use mockito-core instead of mockito-all 

to prevent NoSuchMethodError: org.hamcrest.Matcher ...

Bug 7662 related
Change-Id: I6988023775e35ca3e0babb29aa90b9e1c4eb30fa
Signed-off-by: Michael Vorburger <vorburger@redhat.com>