Update git submodules
* Update docs/submodules/releng/builder from branch 'master'
  to f092ec7cac28de4af848b1aea4f3d80a87360908
  - Use pip freeze instead of pipdeptree
    
    pipdeptree started failing with the below error:
    
    $ pipdeptree
    Traceback (most recent call last):
      File "/tmp/jamovenv/bin/pipdeptree", line 7, in <module>
        from pipdeptree import main
      File "/tmp/jamovenv/lib/python2.7/site-packages/pipdeptree.py",
      line 20, in <module>
        from pip import get_installed_distributions, FrozenRequirement
    ImportError: cannot import name get_installed_distributions
    
    I don't know how to resolve it at this time, but pip
    freeze will still give us a listing of package versions
    (just not as pretty) which is the point of it all.
    
    Change-Id: Ibaba6dbb498fc61dd9543c06cc30bc57be91763c
    Signed-off-by: Jamo Luhrsen <jluhrsen@redhat.com>