Update patch set 9
Patch Set 9:

(2 comments)

> (2 comments)
 > 
 > Script seems generally fine to me but ran into a few issues and
 > questions below.
 > 
 > * I thought we already converted the openstack guide?
 > 
 > * I was unable to successfully build the developer-guide, seems
 > like the makeRST might not be putting the migrated files in the
 > same path that the TOC is expecting?
 > 
 > docs_autotranslation/index.rst:42: WARNING: toctree contains
 > reference to nonexisting document 'developer-guide/index'
 > 
 > * I saw 2 types errors when I generated, one about invalid option
 > block called "figure" and another about "backrefs" are they
 > expected?
 > 
 > /home/user/git/odl/docs/docs_autotranslation/user-guide-autogenerated/group-based-policy-user-guide.rst:103:
 > ERROR: Error in "figure" directive:
 > invalid option block.
 > 
 > .. figure:: ./images/groupbasedpolicy/GBPTerminology1.png
 > :alt: GBP Access Model Terminology - Endpoints, EndpointGroups,
 > Contract
 > 
 > GBP Access Model Terminology - Endpoints, EndpointGroups, Contract
 > 
 > /home/user/git/odl/docs/docs_autotranslation/user-guide-autogenerated/group-based-policy-user-guide.rst::
 > ERROR: Anonymous hyperlink mismatch: 1 references but 0 targets.
 > See "backrefs" attribute for IDs.

 > (2 comments)
 > 
 > Script seems generally fine to me but ran into a few issues and
 > questions below.
 > 
 > * I thought we already converted the openstack guide?
 > 
 > * I was unable to successfully build the developer-guide, seems
 > like the makeRST might not be putting the migrated files in the
 > same path that the TOC is expecting?
 > 
 > docs_autotranslation/index.rst:42: WARNING: toctree contains
 > reference to nonexisting document 'developer-guide/index'
 > 
 > * I saw 2 types errors when I generated, one about invalid option
 > block called "figure" and another about "backrefs" are they
 > expected?
 > 
 > /home/user/git/odl/docs/docs_autotranslation/user-guide-autogenerated/group-based-policy-user-guide.rst:103:
 > ERROR: Error in "figure" directive:
 > invalid option block.
 > 
 > .. figure:: ./images/groupbasedpolicy/GBPTerminology1.png
 > :alt: GBP Access Model Terminology - Endpoints, EndpointGroups,
 > Contract
 > 
 > GBP Access Model Terminology - Endpoints, EndpointGroups, Contract
 > 
 > /home/user/git/odl/docs/docs_autotranslation/user-guide-autogenerated/group-based-policy-user-guide.rst::
 > ERROR: Anonymous hyperlink mismatch: 1 references but 0 targets.
 > See "backrefs" attribute for IDs.

I have changed the index.rst and include the openstack guide which has been converted. 
You should be able to build the developer and user guide now by running makeRST.sh. There was an path error in index.rst.
For those build warnings/errors, it's hard to fix without manually checking.

Patch-set: 9
Label: Verified=0