Updated git submodules
Project: netvirt stable/carbon 507b59be0f700e8298a331310c47b1a768344933

Fix NullPointerException in QosInterfaceStateChangeListener

2017-06-27 18:29:37,596 | ERROR | eChangeHandler-0 |
QosInterfaceStateChangeListener  | 344 -
org.opendaylight.netvirt.qosservice-impl - 0.4.1.SNAPSHOT |
Qos:Exception caught in Interface Operational State Up event

java.lang.NullPointerException: the Function passed to
Optional.transform() must not return null.
        at
com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)[38:com.google.guava:18.0.0]
        at
com.google.common.base.Present.transform(Present.java:71)[38:com.google.guava:18.0.0]
        at
org.opendaylight.netvirt.qosservice.QosInterfaceStateChangeListener.getNeutronPort(QosInterfaceStateChangeListener.java:117)[344:org.opendaylight.netvirt.qosservice-impl:0.4.1.SNAPSHOT]

Change-Id: Ic2a6750ac605dedeb61572689f62a97c811b8fa2
Signed-off-by: Michael Vorburger <vorburger@redhat.com>
(cherry picked from commit a32ac7563dda41f0b581b4e93826bee7ff4bee20)