Update git submodules
* Update docs/submodules/aaa from branch 'master'
  to 5ed7382260e82cac957ded98cd863557f9c0d1cd
  - Merge "Move AAAShiroProvider class in act into separate package"
  - Move AAAShiroProvider class in act into separate package
    
    There are two classes named AAAShiroProvider both in package
    org.opendaylight.aaa; one in artifact (and OSGi bundle) aaa-shiro and
    another one in aaa-shiro-act.
    
    As far as I understand the AAA code, this does not seem to be done
    intentionally for any particular reason, probably just historical
    copy/paste.
    
    Under OSGi, this doesn't really cause any major issues (other than it
    being "really not nice", possibly confusing, and theoretically causing
    issues if one were to use package import), as the two AAAShiroProvider
    are loaded into separate ClassLoaders in their respective bundles.
    
    When attempting to use AAA in a (non-OSGi) flat classpath environment
    however, then the present situation, leads to this error:
    
    [main] ERROR org.apache.shiro.web.env.EnvironmentLoader - Shiro
    environment initialization failed
    java.lang.NoSuchMethodError:
    org.opendaylight.aaa.AAAShiroProvider.getInstance()Lorg/opendaylight/aaa/AAAShiroProvider;
    	at org.opendaylight.aaa.shiro.web.env.KarafIniWebEnvironment.init(KarafIniWebEnvironment.java:67)
    
    This change fixes above, for non-OSGi test envs, but seems a reasonable
    clean up if for the standard deployment model of running ODL in OSGi.
    
    Change-Id: Ia5d34e6f3ecf9d6539bdac9537b8628dcde59049
    Signed-off-by: Michael Vorburger <vorburger@redhat.com>